<h1 align="center">Inferential Statistics</h1>
<br/>

<img src="../images/inferential.png" alt="Inferential_Stats" style="width: 400px;"/>
<br/><br/>
Image Source : https://www.kissclipart.com/colorful-dice-clipart-dice-clip-art-1qud0q/

## Explainer Video

In [2]:
from IPython.display import HTML
HTML('<iframe src="https://player.vimeo.com/video/281606251" width="800" height="600" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>')

## <h1 align="center">Making Inference from Data</h1>
<br/>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math

## Housing Dataset
***

Let's start by loading the dataset.

In [3]:
df1 = pd.read_csv('../data/train.csv')
df1.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

<img src="../images/icon/ppt-icons.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

##  Mini-Challenge - 1
***
### Instructions
* Consider a sample of LotArea of 600 houses at random from 1460 houses and print it's mean and then check it with the entire population mean of LotArea

## Weather Dataset
***

Let's start by loading the dataset.

In [4]:
df2 = pd.read_csv('../data/weather_2012.csv')
df2.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

<img src="../images/icon/ppt-icons.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

##  Mini-Challenge - 2
***
### Instructions
* Find the 95% confidence interval for the Temperature column in the weather dataset for a sample size of 2000.

<img src="../images/icon/ppt-icons.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

##  Mini-Challenge - 3
***
### Instructions
* For the Weather dataset, let the null and alternate hypothesis be as follows:
```python
Null Hypothesis: The mean of Temperature when it is snow ('Snow Showers') is the same as the population mean.
Alternate Hypothesis: The mean of Temperature when it is snow ('Snow Showers') is different than the population 
mean.
```
Test the above hypothesis at 90% significance level and print True if we do not reject the null hypothesis. 
Calculate two-sided test for the null hypothesis using `stats.ttest_1samp`

## Quiz

Q1. Inferential statistics enable you to
```python 
A. decide if the research hypothesis is true. 
B. decide if the null hypothesis is false. 
C. estimate population parameters. 
D. decide if your research results are meaningful. 
   
```
Q2. Statistical inference is the part of hypothesis testing that
```python
A. helps you to prove the null hypothesis is false. 
B. helps you to determine the probability that a sample is from one population or another. 
C. helps you do determine if the research hypothesis is powerful. 
D. helps you to determine if the research hypothesis is true. 

```
Q3. A distribution of sample means is a collection of sample means from
```python 
A. samples of different sizes from different populations. 
B. samples of size N from different populations. 
C. samples of size N from the same population. 
D. samples of different sizes from the same population. 

```
Q4. The mean of a sampling distribution of a sample statistic is called
```python 
A. the mean of the means. 
B. the standard error. 
C. the central limit. 
D. the expected value. 

```
Q5. For which of the following sample sizes would the standard error of the distribution of means be the smallest?
```python 
A. 1 
B. 100 
C. 200 
D. 42 

```
Q6. The name of the central limit theorem implies that
```python 
A. sample means are always central to hypothesis testing. 
B. there is no limit to how many samples can be drawn from a population. 
C. sample means tend to cluster around the central population value. 
D. the name of the central limit theorem has nothing to do with what it implies. 

```
Q7. The critical region contains
```python 
A. the statistical values for which you would retain the null hypothesis. 
B. the region of the distribution between your observed statistic and the critical value. 
C. the statistical values for which you would reject the null hypothesis. 
D. the set of values for which the sample statistic is accurate. 

```
Q8. A friend of mine studies the effects of praise on happiness. She believes that children who receive praise are happier overall than children who do not receive praise. She measures happiness by counting the number of times a child smiles in a one hour period. She knows that in the population of children who do not receive praise smiles average 4 times per hour with a standard deviation of .5, and that these data are normally distributed. She selects a sample of 100 children whom she knows receive praise and finds that they smile an average of 3.5 times per hour.

I should
```python
A. reject the null hypothesis and risk making a Type II error. 
B. reject the null hypothesis and risk making a Type I error. 
C. retain the null hypothesis and claim that praise does not affect happiness. 
D. retain the null hypothesis and state that the results of the study are inconclusive. 

```

# Thank You
***
### Next Session: Make your first prediction with Linear Regression
For more queries - Reach out to academics@greyatom.com